Update the install instructions to use `install-theos`
theos/theos.dev pull request #24
Opened 2022-10-30 16:40 UTC by L1ghtmann

What does this implement/fix? Explain your changes.
---------------------------------------------------
See title

Does this close any currently open issues?
------------------------------------------
No, but it will supersede #20

Any relevant logs, error output, etc?
-------------------------------------
N/A

Any other comments?
-------------------
It's probably a good idea to check the installer on all platforms once more before this is merged. I tested it as I made changes and Uroboro ran it through additional VM tests, but a third once over wouldn't hurt. 

Where has this been tested?
---------------------------
**Operating System:** …

**Platform:** …

**Target Platform:** …

**Toolchain Version:** …

**SDK Version:** …

2022-11-26 16:11 UTC, uroboro requested changes
Looks good. I checked the preview site and found one issue with links in the subscript tags

2022-11-26 16:11 UTC, uroboro commented on docs/Installation-Linux.md
> +	<sup>1</sup> In order to use <i>sudo</i>, your non-root user will have to be added to the sudoers file (/etc/sudoers). For more information, see <a href=https://wiki.archlinux.org/title/Sudo#Example
This link does not work in the preview. Does markdown work here?

```suggestion
	<sup>1</sup> In order to use <i>sudo</i>, your non-root user will have to be added to the sudoers file (/etc/sudoers). For more information, see [here](https://wiki.archlinux.org/title/Sudo#Example_entries>).
```

2022-11-26 16:11 UTC, uroboro commented on docs/Installation-iOS.md
> +	<sup>1</sup> In order to use <i>sudo</i>, your non-root user will have to be added to the sudoers file (/etc/sudoers). For more information, see <a href=https://wiki.archlinux.org/title/Sudo#Example
Same issue as in the iOS page

2022-12-20 00:33 UTC, uroboro approved these changes

2023-01-29 11:46 UTC, kirb approved these changes
LGTM, I want to get some mileage out of the installer ASAP so I think it's worth merging this now.

2023-01-29 11:47 UTC, merged